language: java
dist: trusty

env:
  global:
   #   "travis encrypt" command using the project repo's public key
   # - secure: ""

addons:
  coverity_scan:
    project:
      name: "cmoine/arangobee"
      description: "Build submitted via Travis CI"
    notification_email: christophe.moine@free.fr
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master
